const AIDES = [
  {
    id: 1,
    nom: "Crédit d'impôt recherche (CIR)",
    organisme: "État",
    type: "credit_impot",
    secteurs: ["industrie", "tech"],
    regions: ["national"],
    montantMax: null, // pas de plafond fixe
    tauxFinancement: 0.3,
    dateLimite: "2026-12-31",
    description: "Soutien aux dépenses de R&D des entreprises.",
  },
  {
    id: 2,
    nom: "Aide à la décarbonation industrielle",
    organisme: "ADEME",
    type: "subvention",
    secteurs: ["industrie"],
    regions: ["national"],
    montantMax: 5000000,
    tauxFinancement: 0.4,
    dateLimite: "2026-09-30",
    description: "Financement de projets de réduction des émissions.",
  },
  {
    id: 3,
    nom: "Prêt Croissance Industrie",
    organisme: "Bpifrance",
    type: "pret",
    secteurs: ["industrie"],
    regions: ["national"],
    montantMax: 5000000,
    tauxFinancement: null,
    dateLimite: "2026-11-15",
    description: "Prêt sans garantie pour financer la croissance.",
  },
  {
    id: 4,
    nom: "Fonds régional d'innovation",
    organisme: "Région Hauts-de-France",
    type: "subvention",
    secteurs: ["industrie", "tech"],
    regions: ["hauts-de-france"],
    montantMax: 100000,
    tauxFinancement: 0.5,
    dateLimite: "2026-07-31",
    description: "Soutien aux projets innovants des PME régionales.",
  },
  {
    id: 5,
    nom: "Aide à l'investissement productif",
    organisme: "Région Hauts-de-France",
    type: "avance_remboursable",
    secteurs: ["industrie", "btp"],
    regions: ["hauts-de-france", "normandie"],
    montantMax: 200000,
    tauxFinancement: 0.3,
    dateLimite: "2026-10-01",
    description: "Avance pour moderniser l'outil de production.",
  },
  {
    id: 6,
    nom: "FEDER – Innovation PME",
    organisme: "Union Européenne",
    type: "subvention",
    secteurs: ["industrie", "tech", "btp"],
    regions: ["hauts-de-france", "national"],
    montantMax: 1000000,
    tauxFinancement: 0.5,
    dateLimite: "2026-08-20",
    description: "Cofinancement européen de projets innovants.",
  },
];

export default AIDES;